### ISSUE TITLE
4.5.2 seems to load only from cache

### ISSUE THREAD

**Issue by uli-on** [scoute-dich/Weather#27] opened 2019-12-27 10:19 UTC
I've recently updated from 4.4 to 4.5.2, and from then on the app couldn't receive fresh data. On opening the app I had data from two days ago, and pulling down the page made a splash screen appear "Can't connect to the internet, loading from cache instead" (or the like), though other apps did have internet connection and could access to https://m.wetterdienst.de

De-installing 4.5.2 and re-installing 4.4 brought back functionality. (Android is 6.0.1, Webview is 79.0.3945.93.)

**Comment by mstmob** [comment] 2019-12-30 10:18
I have the same issue if I am connected via WLAN. Turning off wlan and only connect via mobile services however brought back the expected behaviour. 
So maybe it is an network permission problem?!

**Comment by jklmnn** [comment] 2020-01-02 08:25
I can confirm the issue. It only seems to work with mobile data without using a VPN.

**Comment by jklmnn** [comment] 2020-01-02 19:12
I added a fix in #28 that works for me at least. Can someone else please check if it works for you, too?

**Comment by scoute-dich** [comment] 2020-01-10 09:19
I've merged the pull request from @jklmnn 
For me it's working. But I never had this issue on Android10. So if anyone can test, here's the apk (just rename it).
[app-debug.zip](https://github.com/scoute-dich/Weather/files/4044819/app-debug.zip)

**Comment by uli-on** [comment] 2020-01-10 10:21
Sorry, doesn't work for me.

Am 10. Januar 2020 10:19:13 schrieb Gaukler Faun <notifications@github.com>:

**Comment by scoute-dich** [comment] 2020-01-10 10:29
New approach. It also doesn't work for me running Android10. New version:
[Uploading app-debug.zip…]()

**Comment by scoute-dich** [comment] 2020-01-10 10:32
New approach. It also doesn't work for me running Android10. New version:
[app-debug.zip](https://github.com/scoute-dich/Weather/files/4045145/app-debug.zip)

**Comment by uli-on** [comment] 2020-01-10 10:41
App behaviour remains, see my first post for details, sorry to say.

**Comment by uli-on** [comment] 2020-01-10 11:02
I revoke, apologies! It's been my firewall. Though a factual update, I had
to de-install 4.4 and should have set up a new rule for 4.5.2, but didn't
think of it early enough. All fine now.

**Comment by uli-on** [comment] 2020-01-10 11:47
I've to use this thread for posting a new issue as Github seems to tighten
technical details using the GH website and I can't log in any longer (error
What? Your browser did something unexpected)


The footer bar icon for Statistics Graph is mis-connected, it opens the
normal, local 3-hours forecast.

**Closed** 2020-02-03 11:10 UTC
